Repository Team-Alilm/alilm-fe, pull requests merged in 2024-10, with the labels that each got.

#23 feat: 온보딩 모달 구현
  public/images/onboarding_1.png
  public/images/onboarding_2.png
  src/app/layout.tsx
  src/app/onboarding/index.css.ts
  src/app/onboarding/page.tsx
  src/app/page.tsx
  src/components/common/modal/ModalPortal/index.tsx
  src/components/main/onboarding/index.css.ts
  src/components/main/onboarding/index.tsx
  src/components/product/product-card-list/index.tsx
  src/hooks/common/use-boolean-state.ts
Labels: frontend

#26 fix: basket-card - user png 이미지 렌더링 문제 svg 파일로 수정
  .vscode/settings.json
  package.json
  pnpm-lock.yaml
  src/components/create/product-options-form/index.tsx
  src/components/icons/icon-svg.ts
  src/components/icons/icon.css.ts
  src/components/icons/index.tsx
  src/components/icons/user-two-person.tsx
  src/components/product/basket-card/index.css.ts
  src/components/product/basket-card/index.tsx
  src/libs/api/client.ts
Labels: enhancement, frontend

#28 feat: 온보딩 모달 수정
  public/images/onboarding_1.png
  public/images/onboarding_1.webp
  public/images/onboarding_2.png
  public/images/onboarding_2.webp
  src/app/page.tsx
  src/components/main/onboarding/index.css.ts
  src/components/main/onboarding/index.tsx
Labels: frontend

#42 feat: 온보딩 pagination active bullet 색상 변경
  src/components/main/onboarding/index.css.ts
Labels: frontend

#51 feat: 카카오 로그인 버튼 이미지 수정
  src/app/login/page.tsx
  src/components/icons/icon-svg.ts
  src/components/icons/kakao-login-btn.tsx
Labels: frontend

#55 global fonts, fonts, token color 적용
  public/fonts/Pretendard-Black.woff
  public/fonts/Pretendard-SemiBold.woff
  src/app/layout.tsx
  src/components/create/product-options-form/index.tsx
  src/components/product/basket-badge/index.css.ts
  src/components/product/basket-card/index.css.ts
  src/components/product/basket-card/index.tsx
  src/components/ui/button/button.css.ts
  src/styles/colors.css.ts
  src/styles/fonts.css.ts
  src/styles/global.css.ts
  src/styles/index.ts
  src/styles/local-fonts.ts
  src/styles/tokens.css.ts
Labels: enhancement
